version: '3.8'

services:
  sabledb:
    image: sabledb:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6379:6379"
    volumes:
      - sabledb_data:/var/lib/sabledb/data/sabledb.db
    entrypoint: ["sabledb", "/etc/sabledb/server.ini"]
    restart: unless-stopped

volumes:
  sabledb_data: {}